

// Overwriting confs of "/etc/apt/apt.conf.d/20auto-upgrades"
	APT::Periodic::Update-Package-Lists "1"; // update package list (daily), equivalent to "sudo apt update command"
	APT::Periodic::Unattended-Upgrade "1"; // enable automatic updates (daily) 
	APT::Periodic::Download-Upgradeable-Packages "1"; // enable automatic download of new packages (daily)
	APT::Periodic::AutocleanInterval "7"; // clean APT, like to remove the packages not necessary anymore like legacy dependencies (weekly)


// Overwriting confs of "/etc/apt/apt.conf.d/50unattended-upgrades"

	// Personalize what should be upgraded. Here:
	// - allowed: security patches
	// - blocked: packages updates
	// Note: major OS version upgrade are not in scope of unattended-upgrade's job (only the minor)

	Unattended-Upgrade::Allowed-Origins {
		"${distro_id}:${distro_codename}";
		"${distro_id}:${distro_codename}-security";
		"${distro_id}ESMApps:${distro_codename}-apps-security";
		"${distro_id}ESM:${distro_codename}-infra-security";

		// Packages automatic updates: disabled
		// "${distro_id}:${distro_codename}-updates";

		// To strictly avoid:
		// "${distro_id}:${distro_codename}-proposed"; // "-proposed": updates in testing phase
		// "${distro_id}:${distro_codename}-backports"; // "-backports": for older Ubuntu version, allow updates for software on top of the OS
	};

	// disable automatic reboot (if were to set to true: configure in advance the reboot time, but not used here)
	Unattended-Upgrade::Automatic-Reboot "false";
	Unattended-Upgrade::Automatic-Reboot-Time "02:00";	

	// Email to send notifications for problems or packages upgrades
	Unattended-Upgrade::Mail "arnaudlayec@gmail.com";
	Unattended-Upgrade::MailReport "on-change";
	
	// Remove unused packages & dependencies
	Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";
	Unattended-Upgrade::Remove-New-Unused-Dependencies "true";
	Unattended-Upgrade::Remove-Unused-Dependencies "true";
	
	// Download bandwidth threshold (kb/sec)
	Acquire::http::Dl-Limit "1024";
	Unattended-Upgrade::Skip-Updates-On-Metered-Connections "false"; // should not be relevant, but by precaution

	// Not relevant because "dev release" aren't LTS, but disable it by precaution anyway
	Unattended-Upgrade::DevRelease "false";
