Port 2232
PermitRootLogin no

PubkeyAuthentication yes
PasswordAuthentication no
PermitEmptyPasswords no

KbdInteractiveAuthentication yes
KerberosAuthentication no
GSSAPIAuthentication no

UsePAM yes
ChallengeResponseAuthentication yes
AuthenticationMethods publickey,keyboard-interactive
AllowAgentForwarding no

AllowUsers odoo
