#https://manpages.ubuntu.com/manpages/jammy/man8/logrotate.8.html#:~:text=logrotate%20is%20designed%20to%20ease,when%20it%20grows%20too%20large.

/var/log/odoo/*.log {
	size 1M # Log files are rotated only if they  grow  bigger  than  size  bytes
    # other possibility: frequency, with "daily", "weekly", "monthly" or "yearly" args
    
	rotate 20 # Log files are rotated count times before being removed
	noolddir # Logs are rotated in the directory they  normally  reside  in
    
	su root root # "su user group" : Rotate  log files set under this user and group instead of using default user/group
    
    copytruncate # pointer of the application stays on the same file ; instead of logrotate to move the log file and creates a new one
    
	compress # Old  versions  of  log  files  are  compressed  with  gzip
	delaycompress # Postpone  compression  of  the  previous log file to the next rotation cycle
    
	missingok # If the log file is missing, go on to the next one without issuing an error message
    notifempty # Do not rotate the log if it is empty
}
