
upstream odoo-prod {
	server 127.0.0.1:8069 weight=1 fail_timeout=3000s;
}
upstream odoochat-prod {
	server 127.0.0.1:8072 weight=1;
}
map $http_upgrade $connection_upgrade {
  default upgrade;
  ''      close;
}

# http -> https
server {
	listen 80;
    listen [::]:80;
	server_name odoo.asj.com;
	
    root /var/www/html;
    location ~ /.well-known {
		allow all;
	}
    location / {
		rewrite ^(.*) https://$host$1 permanent;
    }
}

server {
	listen 443 ssl;
    listen [::]:443 ssl;
	
    # List the DNS names from which you want to be able to access Odoo
	server_name odoo.asj.com;
	
    # Sometimes, Odoo can be slow to answer, for example when we ask him
    # to generate a large accounting report... we set it to 30 min
	proxy_read_timeout 1800s;
	proxy_connect_timeout 1800s;
	proxy_send_timeout 1800s;
	
    # increase proxy buffer to handle some Odoo web requests
    proxy_buffers 16 64k;
    proxy_buffer_size 128k;
	
    # Allow HTTP compression
    client_max_body_size 64m;
    gzip             on;
    gzip_min_length  400;
    gzip_proxied     expired no-cache no-store private auth;
    gzip_types       text/css text/scss text/plain text/xml application/xml application/json application/javascript;
	
	# Add Headers for odoo proxy mode
	proxy_set_header X-Forwarded-Host $host;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header X-Forwarded-Proto $scheme;
	proxy_set_header X-Real-IP $remote_addr;
	
	# check Odoo recommendations: https://www.odoo.com/documentation/17.0/administration/on_premise/deploy.html
	# SSL parameters
	ssl_protocols TLSv1.2 TLSv1.3;
	ssl_session_timeout 30m;
	# ssl_certificate /etc/letsencrypt/live/odoo.asj.com/fullchain.pem;
	# ssl_certificate_key /etc/letsencrypt/live/odoo.asj.com/privkey.pem;
	ssl_certificate /etc/ssl/certs/odoo-selfsigned.crt;
	ssl_certificate_key /etc/ssl/private/odoo-selfsigned.key;
	ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSAAES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHERSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
	ssl_prefer_server_ciphers off;

	# log
	access_log /var/log/nginx/odoo-prod.access.log;
	error_log /var/log/nginx/odoo-prod.error.log;

	# Redirect websocket requests to odoo gevent port
	location /websocket {
		proxy_pass http://odoochat-prod;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection $connection_upgrade;

		# add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";
		## requires nginx 1.19.8 :
		# proxy_cookie_flags session_id samesite=lax secure; 
	}

	# Redirect requests to odoo backend server
	location / {
        # Nginx passes requests to Odoo
		proxy_pass http://odoo-prod;
		
        # force timeouts if the backend dies
        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;
		
        # The parameter proxy_redirect is important if we use Odoo on localhost
		proxy_redirect off;
		
		# Enforce the client to request SSL on this domain for 1 year
		add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";
		## requires nginx 1.19.8:
		# proxy_cookie_flags session_id samesite=lax secure;
	}
	
	# cache static data
	location ~* /web/static/ {
		proxy_cache_valid 200 60m;
		proxy_buffering on;
		expires 86400;
		proxy_pass http://odoo-prod;
	}
}