
# http -> https
server {
	listen 80;
    listen [::]:80;
	server_name pgadmin4.abbaye-aiguebelle.fr;
	
	access_log /var/log/nginx/pgadmin4.access.log;
	error_log /var/log/nginx/pgadmin4.error.log;
	
	rewrite ^/.*$ https://$host$request_uri? permanent;
}

server {
	listen 443 ssl;
    listen [::]:443 ssl;
	server_name pgadmin4.abbaye-aiguebelle.fr;

	proxy_read_timeout 720s;
	proxy_connect_timeout 720s;
	proxy_send_timeout 720s;
	
	# SSL parameters
	ssl_certificate /etc/letsencrypt/live/pgadmin4.abbaye-aiguebelle.fr/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/pgadmin4.abbaye-aiguebelle.fr/privkey.pem;
	ssl_session_timeout 30m;
	ssl_protocols TLSv1.2 TLSv1.3;
	ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSAAES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHERSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
	ssl_prefer_server_ciphers off;

	# log
	access_log /var/log/nginx/pgadmin4.access.log;
	error_log /var/log/nginx/pgadmin4.error.log;

	# Redirect requests to backend server
	location / {
		proxy_redirect off;
		# Add Headers for proxy mode
		proxy_pass http://unix:/tmp/pgadmin4.sock;
		include proxy_params;
		
		add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";
		# requires nginx 1.19.8:
		# proxy_cookie_flags session_id samesite=lax secure;
	}
	
	# common gzip
	gzip_types text/css text/scss text/plain text/xml application/xml application/json application/javascript;
	
	gzip on;
}