[Unit]
Description=Odoo-DEV
Requires=postgresql.service
After=network.target postgresql.service

[Service]
Type=simple
User=odoo
Group=odoo
WorkingDirectory=/home/odoo/o18
ExecStart=/home/odoo/o18/bin/python odoo-bin -c /etc/odoo/staging.conf
KillMode=mixed

[Install]
WantedBy=multi-user.target
