[Unit]
Description=Odoo
Requires=postgresql.service
After=network.target postgresql.service

[Service]
Type=simple
User=odoo
Group=odoo
ExecStart=/home/odoo/o18/bin/python /home/odoo/o18/odoo-bin -c /etc/odoo/prod.conf
KillMode=mixed

[Install]
WantedBy=multi-user.target

