
#	Sources:
#	https://wiki.postgresql.org/wiki/Performance_Optimization
#	https://wiki.postgresql.org/wiki/Tuning_Your_PostgreSQL_Server
#	https://www.enterprisedb.com/postgres-tutorials/how-tune-postgresql-memory

# Postgre Security
	# Best is to disable TCP socket to only allow UNIX. If not possible, restrict to "localhost"
	# file: pg_hba.conf
	# location: /etc/postgresql/16/main/pg_hba.conf
	listen_addresses = localhost

# Postgre performance
	
	# Determines the amount of memory that can be used by PostgreSQL for shared memory buffers
	# Advised: 25% of RAM (default: 128MB)
	shared_buffers = 1GB
	# unit : number of blocks (or buffers), where each buffer is 8192Ko (value of BLCKSZ)
	# so for 1GB = 1024*1024*1024 octets = 1073741824 octets ; 1073741824/8192=131072 blocks

	# Not an allocation, just maximum limit
	# Advised : 50% of RAM
	effective_cache_size = 2GB

	# Tells how the checkpoint writes need to be completed within the checkout_timeout interval
	# Default: 0.9
	checkpoint_completion_target = 0.9

	# Maximum amount of memory A QUERY can use for its operation, such as sorts, hash tables, etc.
	# Default: 4MB
	work_mem = 100MB

	# Amount of memory allocated to perform maintenance activities on the database, like creating indexes, altering tables, vacuuming, data loading, etc
	# Optimal way for this would be to perform as many operations as possible in memory and write the final output to disk
	# Default: 64MB, recommended 5% of total RAM
	maintenance_work_mem = 200MB

	# Amount of shared_buffers memory to buffer before it can be written to disk
	# 16MB is the maximum and very safe for modern server
	wal_buffers = 16MB

	# max_connections = max(4 * number of CPU cores, 100)
	# Default in 22.04 : 100
	max_connections=100

	# Query cost estimator : mettre les 2 à la même valeur
	# Info issue de https://amplitude.engineering/how-a-single-postgresql-config-change-improved-slow-query-performance-by-50x-85593b8991b0
	seq_page_cost = 1.0
	random_page_cost = 1.0

	# Number of workers that autovacuum has. Each table can have only 1 worker working on it so more workers helps in more parallel and frequent work
	# Default: 3
	autovacuum_max_workers = 5

	# Prevent excessive load on the database server due to autovacuum (I/O quota)
	autovacuum_vacuum_cost_limit = 3000
