[Unit]
Description=Pgadmin4
Requires=postgresql.service
After=network.target postgresql.service

[Service]
Type=simple
User=pgadmin4
Group=pgadmin4
WorkingDirectory=/home/pgadmin4/env
ExecStart=bash -c "/usr/bin/screen -s pgadmin4 -dm bash -c 'source bin/activate; gunicorn --bind unix:/tmp/pgadmin4.sock --workers=1 --threads=25 --chdir /home/pgadmin4/env/lib/python3.10/site-packages/pgadmin4 pgAdmin4:app'"
KillMode=mixed

[Install]
WantedBy=multi-user.target


# Other tried conf:
# WorkingDirectory=/home/pgadmin4/env
# ExecStart=/home/pgadmin4/env/bin/python /home/pgadmin4/env/lib/python3.10/site-packages/gunicorn --bind unix:/tmp/pgadmin4.sock --workers=1 --threads=25 --chdir /home/pgadmin4/env/lib/python3.10/site-packages/pgadmin4 pgAdmin4:app
# -> returns "ModuleNotFoundError: No module named 'http.server'"
