
# ===== CLIENT VPN ===========
[Interface]
# Adresse IP du client à l'intérieur du VPN
Address = 10.4.99.20/32
# Clef privée du client
PrivateKey = aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
#DNS = 192.168.120.254
MTU = 1340

# ==== SERVEUR VPN ==========
[Peer]
# Clef publique du du serveur
PublicKey = aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
# Adresse et port du serveur
Endpoint = miluni.fr:50234
#Endpoint = 77.194.254.193:21211
# Range d'adresses IP qui doivent être routées à travers le VPN
# Il faut à la fois mettre le réseau du VPN ET le réseau distant
#AllowedIPs = 10.28.11.0/24
#AllowedIPs = 10.4.99.0/24, 192.168.1.0/24
AllowedIPs = 10.4.99.0/24
# keepalive pour maintenir la connexion si le client se trouve derrière un NAT
PersistentKeepalive = 25
